using System.ComponentModel;

namespace VTS
{
    // CANNOT USE REQUEST AT THE END
    // IN REFLECTION
    public enum MessageTypeEnum
    {
        [Description("APIError")]// NO REQUEST
        APIError,
        [Description("APIStateRequest")]
        APIStateRequest,
        [Description("AuthenticationTokenRequest")]
        AuthenticationTokenRequest,
        [Description("StatisticsRequest")]
        StatisticsRequest,
        [Description("VTSFolderInfoRequest")]
        FolderInfoRequest,
        [Description("CurrentModelRequest")]
        CurrentModelRequest,
        [Description("AvailableModelsRequest")]
        AvailableModelsRequest,
        [Description("ModelLoadRequest")]
        ModelLoadRequest,
        [Description("MoveModelRequest")]
        MoveModelRequest,
        [Description("HotkeysInCurrentModelRequest")]
        HotkeysInCurrentModelRequest,
        [Description("HotkeyTriggerRequest")]
        HotkeyTriggerRequest,
        [Description("ArtMeshListRequest")]
        ArtMeshListRequest,
        [Description("ColorTintRequest")]
        ColorTintRequest,
        [Description("SceneColorOverlayInfoRequest")]
        SceneColorOverlayInfoRequest,
        [Description("FaceFoundRequest")]
        FaceFoundRequest,
        [Description("InputParameterListRequest")]
        InputParameterListRequest,
        [Description("ParameterValueRequest")]
        ParameterValueRequest,
        [Description("Live2DParameterListRequest")]
        Live2DParameterListRequest,
        [Description("ParameterCreationRequest")]
        ParameterCreationRequest,
        [Description("ParameterDeletionRequest")]
        ParameterDeletionRequest,
        [Description("InjectParameterDataRequest")]
        InjectParameterDataRequest,
        [Description("ExpressionStateRequest")]
        ExpressionStateRequest,
        [Description("ExpressionActivationRequest")]
        ExpressionActivationRequest,
        [Description("GetCurrentModelPhysicsRequest")]
        GetCurrentModelPhysicsRequest,
        [Description("SetCurrentModelPhysicsRequest")]
        SetCurrentModelPhysicsRequest,
        [Description("NDIConfigRequest")]
        NDIConfigRequest,
        [Description("VTubeStudioAPIStateBroadcast")]
        VTubeStudioAPIStateBroadcast,
        [Description("ItemListRequest")]
        ItemListRequest,
        [Description("ItemListResponse")]
        ItemListResponse,
        [Description("ItemLoadRequest")]
        ItemLoadRequest,
        [Description("ItemLoadResponse")]
        ItemLoadResponse,
        [Description("ItemUnloadRequest")]
        ItemUnloadRequest,
        [Description("ItemUnloadResponse")]
        ItemUnloadResponse,
        [Description("ItemAnimationControlRequest")]
        ItemAnimationControlRequest,
        [Description("ItemAnimationControlResponse")]
        ItemAnimationControlResponse,
        [Description("ItemMoveRequest")]
        ItemMoveRequest,
        [Description("ItemMoveResponse")]
        ItemMoveResponse,
        [Description("ArtMeshSelectionRequest")]
        ArtMeshSelectionRequest,
        [Description("ArtMeshSelectionResponse")]
        ArtMeshSelectionResponse,
        [Description("EventSubscriptionResponse")]
        EventSubscriptionResponse,
        [Description("EventSubscriptionRequest")]
        EventSubscriptionRequest,
        [Description("TestEventSubscriptionRequest")]
        TestEventSubscription,
        [Description("TestEvent")]
        TestEvent,
        [Description("ModelLoadedEvent")]
        ModelLoadedEvent,
        [Description("TrackingStatusChangedEvent")]
        TrackingStatusChangedEvent,
        [Description("BackgroundChangedEvent")]
        BackgroundChangedEvent,
        [Description("ModelConfigChangedEvent")]
        ModelConfigChangedEvent,
        [Description("ModelMovedEvent")]
        ModelMovedEvent,
        [Description("ModelOutlineEvent")]
        ModelOutlineEvent,
    }
}
